# Based on https://github.com/soxofaan/github-actions-sphinx2ghpages

name: Sphinx Documentation to GitHub Pages

on:
  push:
    branches: [ master ]

concurrency: docs-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install package and documentation dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]

    - name: Sphinx build
      run: python -m sphinx -b html docs build

    - name: Commit documentation in gh-pages branch
      run: |
        cd build
        git init -b gh-pages
        touch .nojekyll
        git config --local user.name "GitHub Actions Bot"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update documentation"

    - name: Push gh-pages branch
      run: |
        cd build
        git push --force "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}" gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
